#!/usr/bin/env bash

set -eux

for pkg in $(cat /build/artifacts.txt|awk -F'=' '{print $1}') ; do
    pkgline=$(grep "^$pkg\=" /build/artifacts.txt)
    vers=$(echo $pkgline|cut -d'#' -f1|awk -F'=' '{print $2}')
    deps="--depends postgresql$POSTGRES_VER"
    for d in $(echo $pkgline|awk -F'#' '{print $2}'|tr ',' ' ') ; do
        n=$(echo $d|awk -F'=' '{print $1}')
        _=$(echo $d|awk -F'=' '{print $2}')
        case $n in \
            dblink|pgcrypto) n="postgresql$POSTGRES_VER-contrib"   ;;
            plpy*)           n="postgresql$POSTGRES_VER-plpython3" ;;
        esac
        deps="$deps --depends $n"
    done
    tmp=$(mktemp -d)
    mkdir -p "$tmp/lib"
    mkdir -p "$tmp/share/extension"
    cp -a /build/packaged/$pkg--*.so        "$tmp/lib/"             2>/dev/null && arch=native || arch=all
    cp -a /build/packaged/extension/$pkg--* "$tmp/share/extension/" 2>/dev/null || true
    eval ${GEM_HOME}/bin/fpm \
         --input-type dir \
         --output-type rpm \
         --architecture $arch \
         --name $pkg \
         --version $vers \
         --iteration $ITERATION \
         --prefix /usr/pgsql-$POSTGRES_VER/ \
         --chdir $tmp \
         $deps \
         .
done
